FROM rust:1.84-bookworm

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN cargo install cargo-watch

EXPOSE 3000

CMD ["cargo", "watch", "-x", "run"]
